services:
  - type: web
    name: chuncheon-ai-chatbot
    runtime: python
    buildCommand: "pip install -r requirements_enhanced.txt"
    startCommand: "python enhanced_web_chatbot.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8080
    autoDeploy: false